# warps (JavaScript) - ISOLATED fixing - ENTERPRISE SIZE

projects:
  - path: "/home/rmondo/repos/warps"
    language: "javascript"

languages:
  enabled: ["javascript"]
  auto_detect: false
  javascript:
    linters: ["eslint"]
    type_checker: "tsc"
    test_framework: "jest"
    complexity_threshold: 15
    max_file_lines: 800

priorities:
  p1_static:
    enabled: true
    max_duration_seconds: 300  # 5 min - larger project
    success_threshold: 0.70  # Lower threshold - lots of errors
  p2_tests:
    enabled: true
    adaptive_strategy: true
    success_threshold: 0.70
  p3_coverage:
    enabled: false
  p4_e2e:
    enabled: false

execution:
  max_concurrent_projects: 1
  max_iterations: 5
  max_duration_hours: 4  # More time for enterprise

wrapper:
  path: "/home/rmondo/repos/air-executor/scripts/claude_wrapper.py"
  python_executable: "/home/rmondo/.venv/air-executor/bin/python"
  timeout: 1200

# Setup Optimization: Optional Redis configuration for distributed state sharing
# If Redis is unavailable, system automatically falls back to filesystem markers (.ai-state/)
# Redis provides:
#   - Faster state queries (<10ms vs ~50ms filesystem)
#   - Distributed state sharing across multiple environments
#   - Built-in TTL management (30-day automatic expiration)
state_manager:
  redis_host: "localhost"  # Redis server hostname
  redis_port: 6379          # Redis server port (default: 6379)
  namespace: "warps_fix"    # Key namespace for isolation (prevents cross-project conflicts)

logging:
  level: "INFO"  # Global log level: DEBUG, INFO, WARNING, ERROR
  file: "logs/fix-warps.log"

  # Wrapper-specific logging (passed to claude_wrapper.py)
  wrapper:
    level: "DEBUG"  # Controls claude_wrapper.py stderr logging (INFO or DEBUG)
    show_events: true  # Show [WRAPPER DEBUG] event logs from ClaudeClient

  # Debug logger configuration (DebugLogger component)
  debug:
    enabled: true
    log_dir: "logs/debug"
    log_levels:
      wrapper_responses: false  # Include full wrapper responses in debug logs (verbose)
      wrapper_calls: true       # Log all wrapper calls with timing

git:
  auto_commit: true
  commit_prefix: "fix"
  push_after_commit: true
